web:
  image: netzkontrast/nginx
  ports:
    - "80:80"
  volumes:
    - ./src:/var/www
    - ./src/vhost.conf:/etc/nginx/sites-enabled/vhost.conf
  links:
    - php

php:
  image: netzkontrast/php7
  volumes:
    - ./src/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - ./src:/var/www
    - ./src/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini